// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AiModel = {
    api_key_last_rotated?: string;
    base_input_cost_per_million?: number;
    base_output_cost_per_million?: number;
    context_window?: number;
    created_at?: string;
    edges: AiModelEdges;
    id?: string;
    is_active?: boolean;
    last_rotated_by?: string;
    markup_percentage?: number;
    max_input_tokens?: number;
    max_output_tokens?: number;
    model_code?: string;
    model_name?: string;
    pricing_effective_date?: string;
    provider?: string;
    quality_rating?: number;
    recommended_use_case?: string;
    selling_input_cost_per_million?: number;
    selling_output_cost_per_million?: number;
    speed_rating?: number;
    updated_at?: string;
};

export type AiModelEdges = {
    chat_messages?: Array<ChatMessage> | null;
    rotated_by_admin?: Admin;
    subscription_ai_models_rel?: Array<SubscriptionAiModel> | null;
    subscription_plan?: Array<SubscriptionPlan> | null;
    token_usage_logs?: Array<TokenUsageLog> | null;
};

export type AbuseFlag = {
    action_taken?: string;
    action_taken_at?: string;
    created_at?: string;
    details?: {
        [key: string]: unknown;
    };
    detection_method?: string;
    edges: AbuseFlagEdges;
    flag_type?: string;
    id?: string;
    resolution_notes?: string;
    reviewed_at?: string;
    reviewed_by?: string;
    severity?: string;
    status?: string;
    updated_at?: string;
    user_id?: string;
};

export type AbuseFlagEdges = {
    reviewer?: Admin;
    user?: User;
};

export type AddToProductWatchlistData = {
    message: string;
};

export type AddToProductWatchlistPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * ID of the product to add to watchlist
     */
    product_id: string;
};

export type Admin = {
    created_at?: string;
    created_by?: string;
    edges: AdminEdges;
    email?: string;
    first_name?: string;
    id?: string;
    is_active?: boolean;
    last_login_at?: string;
    last_login_ip?: string;
    last_name?: string;
    permissions?: Array<string> | null;
    role?: string;
    updated_at?: string;
};

export type AdminEdges = {
    created_admins?: Array<Admin> | null;
    creator?: Admin;
    reviewed_abuse_flags?: Array<AbuseFlag> | null;
    rotated_ai_models?: Array<AiModel> | null;
    sessions?: Array<Session> | null;
};

export type AnalysisArtifact = {
    blocks?: Array<{
        [key: string]: unknown;
    }> | null;
    created_at?: string;
    data_sources?: Array<string> | null;
    description?: string;
    edges: AnalysisArtifactEdges;
    generation_cost_usd?: number;
    id?: string;
    parent_artifact_id?: string;
    products_analyzed?: number;
    session_id?: string;
    status?: string;
    title?: string;
    tokens_used?: number;
    updated_at?: string;
    user_id?: string;
    version?: number;
};

export type AnalysisArtifactEdges = {
    children?: Array<AnalysisArtifact> | null;
    parent?: AnalysisArtifact;
    session?: ChatSession;
    triggering_message?: ChatMessage;
    user?: User;
};

export type AuthRegisterData = {
    /**
     * registered user data
     */
    user: User;
};

export type BillingTransaction = {
    admin_notes?: string;
    amount?: number;
    created_at?: string;
    currency?: string;
    description?: string;
    edges: BillingTransactionEdges;
    id?: string;
    metadata?: {
        [key: string]: unknown;
    };
    payment_gateway_url?: string;
    payment_method?: string;
    processed_at?: string;
    queries_count?: number;
    status?: string;
    subscription_period?: string;
    tokens_consumed?: number;
    transaction_type?: string;
    updated_at?: string;
    user_id?: string;
};

export type BillingTransactionEdges = {
    credit_purchases?: Array<CreditPurchase> | null;
    user?: User;
};

export type CacheDeleteData = {
    /**
     * Whether key existed and was deleted
     */
    deleted: boolean;
    key: string;
    success: boolean;
};

export type CacheDeletePayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Cache key to delete
     */
    key: string;
};

export type CacheGetData = {
    /**
     * Whether key exists in cache
     */
    found: boolean;
    key: string;
    /**
     * Cached value (if found)
     */
    value?: unknown;
};

export type CacheGetPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Cache key to retrieve
     */
    key: string;
};

export type CacheSetData = {
    /**
     * When cache entry expires (if TTL set)
     */
    expires_at?: string;
    key: string;
    success: boolean;
};

export type CacheSetPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Cache key to set
     */
    key: string;
    /**
     * Time-to-live in seconds (0 = no expiry)
     */
    ttl_seconds?: number;
    /**
     * Value to cache (JSON serializable)
     */
    value: unknown;
};

export type ChangeUserPasswordPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Confirm new password of the user
     */
    confirm_password: string;
    /**
     * Current password of the user
     */
    current_password: string;
    /**
     * New password of the user
     */
    new_password: string;
};

export type ChartDataPoint = {
    /**
     * Time period label
     */
    name: string;
    /**
     * Average price in IDR
     */
    price: number;
    /**
     * Average rating (0-5 scale)
     */
    rating: number;
    /**
     * Total sales in period
     */
    sales: number;
};

export type ChatMessage = {
    ai_model_id?: string;
    analysis_artifact_id?: string;
    chat_session_id?: string;
    content?: string;
    created_at?: string;
    edges: ChatMessageEdges;
    id?: string;
    metadata?: {
        [key: string]: unknown;
    };
    role?: string;
    user_id?: string;
};

export type ChatMessageEdges = {
    ai_model?: AiModel;
    analysis_artifact?: AnalysisArtifact;
    chat_session?: ChatSession;
    token_usage_logs?: Array<TokenUsageLog> | null;
    user?: User;
};

export type ChatSession = {
    context?: {
        [key: string]: unknown;
    };
    created_at?: string;
    edges: ChatSessionEdges;
    id?: string;
    session_expires_at?: string;
    session_started_at?: string;
    status?: string;
    title?: string;
    updated_at?: string;
    user_id?: string;
};

export type ChatSessionEdges = {
    analysis_artifacts?: Array<AnalysisArtifact> | null;
    messages?: Array<ChatMessage> | null;
    token_usage_logs?: Array<TokenUsageLog> | null;
    user?: User;
};

export type CreateProductPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Current price in IDR
     */
    price_current?: number;
    /**
     * Shop/store name
     */
    shop_name?: string;
    /**
     * Marketplace source
     */
    source?: string;
    /**
     * Product URL
     */
    source_url?: string;
    /**
     * Available stock
     */
    stock?: number;
    /**
     * Product title
     */
    title?: string;
};

export type CreateSessionOutput = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    context?: {
        [key: string]: unknown;
    };
    created_at: string;
    id: string;
    session_expires_at?: string;
    session_started_at: string;
    status: string;
    title: string;
    updated_at: string;
    user_id: string;
};

export type CreateSessionPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Optional session title
     */
    title: string;
};

export type CreditPurchase = {
    billing_transaction_id?: string;
    currency?: string;
    edges: CreditPurchaseEdges;
    expires_at?: string;
    id?: string;
    price?: number;
    purchased_at?: string;
    status?: string;
    tokens_purchased?: number;
    tokens_remaining?: number;
    tokens_used?: number;
    user_id?: string;
};

export type CreditPurchaseEdges = {
    billing_transaction?: BillingTransaction;
    user?: User;
};

export type DeleteOneData = {
    message: string;
};

export type DetailProductData = {
    analytics?: ProductAnalytics;
    historical_snapshots?: Array<ProductSnapshot> | null;
    latest_snapshot?: ProductSnapshot;
    product: Product;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type EventData = {
    /**
     * List of all possible Event enum values
     */
    events: Array<'NotificationCreated' | 'OpportunityCreated' | 'OpportunityFailed' | 'OpportunityUpdated'> | null;
};

export type ExecuteQueryData = {
    /**
     * Column names
     */
    columns: Array<string> | null;
    /**
     * Query execution time in milliseconds
     */
    execution_time_ms: number;
    /**
     * Number of rows returned
     */
    row_count: number;
    /**
     * Query results
     */
    rows: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Whether results were truncated due to max_rows
     */
    truncated: boolean;
};

export type ExecuteQueryPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Maximum rows to return
     */
    max_rows: number;
    /**
     * Query parameters for safety (not implemented yet)
     */
    parameters?: {
        [key: string]: unknown;
    };
    /**
     * SQL query to execute (SELECT only)
     */
    sql: string;
    /**
     * Query timeout in milliseconds
     */
    timeout_ms: number;
    /**
     * User ID for tracking
     */
    user_id: string;
};

export type GetMessagesOutput = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    messages: Array<SendMessageOutput> | null;
    total: number;
};

export type HealthData = {
    /**
     * Individual component health checks
     */
    checks: {
        [key: string]: string;
    };
    /**
     * Service name
     */
    service: string;
    /**
     * Overall service status
     */
    status: string;
    /**
     * Current server time
     */
    timestamp: string;
    /**
     * Service version
     */
    version: string;
};

export type JobHttpHandlerData = {
    task_id: string;
};

export type ListSessionsOutput = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    sessions: Array<CreateSessionOutput> | null;
    total: number;
};

export type LogSystemPayloadJob = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
};

export type LoginAdminOutput = {
    access_token: string;
    access_token_expires_at: number;
    refresh_token: string;
    refresh_token_expires_at: number;
};

export type LoginAdminPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Email of the user
     */
    email: string;
    /**
     * Password of the user
     */
    password: string;
};

export type LoginData = {
    access_token: string;
    access_token_expires_at: number;
    refresh_token: string;
    refresh_token_expires_at: number;
};

export type LoginPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Email of the user
     */
    email: string;
    /**
     * Password of the user
     */
    password: string;
};

export type MarkAsReadAllData = {
    description: string;
    id: string;
    name: string;
};

export type MarkAsReadAllPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description: string;
    /**
     * Name of the item
     */
    name: string;
};

export type MeData = {
    created_at?: string;
    edges: UserEdges;
    email?: string;
    email_verified_at?: string;
    first_name?: string;
    id?: string;
    is_active?: boolean;
    last_name?: string;
    phone_number?: string;
    phone_verified_at?: string;
    updated_at?: string;
};

export type Meta = {
    /**
     * Response status code
     */
    code: number;
    /**
     * Response signature
     */
    signature: string;
    /**
     * Response status
     */
    status: string;
    /**
     * Application version
     */
    version: string;
};

export type MetaPagination = {
    /**
     * Response status code
     */
    code: number;
    /**
     * Pagination information
     */
    pagination: Pagination;
    /**
     * Response signature
     */
    signature: string;
    /**
     * Response status
     */
    status: string;
    /**
     * Application version
     */
    version: string;
};

export type Notification = {
    action?: string;
    archived?: boolean;
    channel?: string;
    created_at?: string;
    dedupe_key?: string;
    delivered_at?: string;
    edges: NotificationEdges;
    expires_at?: string;
    group_key?: string;
    id?: string;
    link?: string;
    message?: string;
    meta?: {
        [key: string]: unknown;
    };
    priority?: string;
    read?: boolean;
    read_at?: string;
    resource_id?: string;
    resource_type?: string;
    sticky?: boolean;
    title?: string;
    type?: string;
    updated_at?: string;
    user_id?: string;
};

export type NotificationEdges = {
    user?: User;
};

export type Pagination = {
    /**
     * Current page number
     */
    page: number;
    /**
     * Number of items per page
     */
    per_page: number;
    /**
     * Total number of items
     */
    total_items: number;
    /**
     * Total number of pages
     */
    total_pages: number;
};

export type Product = {
    category?: string;
    create_time?: string;
    currency?: string;
    discount_percentage?: number;
    edges: ProductEdges;
    failure_count?: number;
    id?: string;
    images?: Array<string> | null;
    last_scraped_at?: string;
    long_description?: string;
    meta?: {
        [key: string]: unknown;
    };
    next_scrape_at?: string;
    package_height_mm?: number;
    package_length_mm?: number;
    package_width_mm?: number;
    price_current?: number;
    price_original?: number;
    priority_score?: number;
    product_rating?: number;
    raw?: {
        [key: string]: unknown;
    };
    review_count?: number;
    scrape_status?: string;
    scraped_at?: string;
    shop_location?: string;
    shop_name?: string;
    shop_rating?: number;
    short_description?: string;
    sold_count?: number;
    source?: string;
    source_id?: string;
    source_url?: string;
    stock?: number;
    thumbnail?: string;
    title?: string;
    update_time?: string;
    url_hash?: string;
    user_interest_count?: number;
    variations?: Array<{
        [key: string]: unknown;
    }> | null;
    weight_grams?: number;
};

export type ProductAnalytics = {
    average_price?: number;
    average_stock_level?: number;
    currently_in_stock: boolean;
    data_source_count: number;
    estimated_sales?: number;
    first_scraped_at?: string;
    highest_price?: number;
    last_scraped_at?: string;
    lowest_price?: number;
    price_change_percentage?: number;
    review_growth: number;
    stock_changes: number;
    total_snapshots: number;
    went_out_of_stock: boolean;
};

export type ProductCalculatePriorityData = {
    /**
     * Suggested next scrape time
     */
    next_scrape?: string;
    /**
     * Calculated priority score (0.1-10.0)
     */
    priority: number;
    product_id: string;
    /**
     * Human-readable reason for priority
     */
    reason: string;
};

export type ProductCalculatePriorityPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Product UUID to calculate priority for
     */
    product_id: string;
};

export type ProductDetailChartData = {
    /**
     * Time-series chart data points
     */
    chart_data: Array<ChartDataPoint> | null;
    period_count: number;
    product_title: string;
    product_url: string;
    range: string;
};

export type ProductEdges = {
    user_products?: Array<UserProduct> | null;
    watchers?: Array<ProductWatchlist> | null;
};

export type ProductHashUrlData = {
    marketplace: string;
    /**
     * URL with tracking parameters removed
     */
    normalized_url: string;
    /**
     * Extracted product identifier
     */
    product_slug?: string;
    /**
     * SHA-256 hash of normalized URL
     */
    url_hash: string;
};

export type ProductHashUrlPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Marketplace name
     */
    marketplace: 'tokopedia' | 'shopee' | 'tiktokshop';
    /**
     * Product URL to hash and normalize
     */
    url: string;
};

export type ProductOverviewCardData = {
    total_new_products: number;
    total_product_categories: number;
    total_products: number;
};

export type ProductSnapshot = {
    category_id: string;
    category_l1: string;
    category_l2: string;
    category_l3: string;
    category_name: string;
    description: string;
    discount_percentage?: number;
    images: Array<string> | null;
    is_available: boolean;
    is_cashback: boolean;
    is_cod: boolean;
    is_free_shipping: boolean;
    is_wholesale: boolean;
    marketplace: string;
    original_price?: number;
    price: number;
    product_id: string;
    product_url: string;
    rating?: number;
    raw_data: string;
    review_1_star: number;
    review_2_star: number;
    review_3_star: number;
    review_4_star: number;
    review_5_star: number;
    review_count: number;
    review_with_description: number;
    review_with_photos: number;
    scrape_version: string;
    scraped_at: string;
    seller_id: string;
    seller_is_official: boolean;
    seller_location: string;
    seller_name: string;
    seller_url: string;
    sold_count: number;
    specifications: string;
    stock: number;
    thumbnail: string;
    title: string;
};

export type ProductWatchlist = {
    added_at?: string;
    edges: ProductWatchlistEdges;
    id?: string;
    notify_price_drop?: boolean;
    notify_rating_change?: boolean;
    notify_stock_available?: boolean;
    product_id?: string;
    target_price?: number;
    user_id?: string;
};

export type ProductWatchlistEdges = {
    product?: Product;
    user?: User;
};

export type RefreshOutput = {
    access_token: string;
    access_token_expires_at: number;
};

export type RefreshPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * The refresh token to use for refreshing the session
     */
    refresh_token: string;
};

export type RegisterPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * email of user
     */
    email: string;
    /**
     * first name of user
     */
    first_name: string;
    /**
     * last name of user
     */
    last_name: string;
    /**
     * password of user
     */
    password: string;
};

export type RemoveProductAsUserProductData = {
    message: string;
};

export type RemoveProductWatchlistData = {
    message: string;
};

export type ResponseAddToProductWatchlistData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: AddToProductWatchlistData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseAuthRegisterData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: AuthRegisterData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseCacheDeleteData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: CacheDeleteData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseCacheGetData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: CacheGetData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseCacheSetData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: CacheSetData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseCreateProductData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: Product;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseDeleteOneData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: DeleteOneData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseDetailProductData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: DetailProductData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseEventData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: EventData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseExecuteQueryData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: ExecuteQueryData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseHealthData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: HealthData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseJobHttpHandlerData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: JobHttpHandlerData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseLoginAdminData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: LoginAdminOutput;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseLoginData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: LoginData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseMarkAsReadAllData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: MarkAsReadAllData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseMeData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: MeData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseMessage = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response message
     */
    message: string;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseNotificationGetAllData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: Array<Notification> | null;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponsePaginationListProductData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: Array<Product> | null;
    /**
     * Response metadata with pagination
     */
    meta: MetaPagination;
};

export type ResponsePaginationListUserProductData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: Array<Product> | null;
    /**
     * Response metadata with pagination
     */
    meta: MetaPagination;
};

export type ResponsePaginationListWatchlistProductData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: Array<Product> | null;
    /**
     * Response metadata with pagination
     */
    meta: MetaPagination;
};

export type ResponseProductCalculatePriorityData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: ProductCalculatePriorityData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseProductDetailChartData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: ProductDetailChartData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseProductHashUrlData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: ProductHashUrlData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseProductOverviewCardData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: ProductOverviewCardData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseRefreshData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: RefreshOutput;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseRemoveProductAsUserProductData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: RemoveProductAsUserProductData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseRemoveProductWatchlistData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: RemoveProductWatchlistData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseShopeeAnalyzeData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: ShopeeAnalyzeData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseTiktokshopAnalyzeData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: TiktokshopAnalyzeData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseTokenpediaAnalyzeData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: TokenpediaAnalyzeData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseTokopediaData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: TokopediaData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseUnreadCountData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: UnreadCountData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseVerifyTokenData = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Response data
     */
    data: VerifyTokenData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ScrapingReward = {
    awarded_at?: string;
    batch_number?: number;
    edges: ScrapingRewardEdges;
    id?: string;
    product_url_hash?: string;
    reward_multiplier?: number;
    tier_multiplier?: number;
    tokens_awarded?: number;
    user_id?: string;
    week_number?: number;
    year?: number;
};

export type ScrapingRewardEdges = {
    user?: User;
};

export type SendMessageOutput = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    ai_model_id?: string;
    analysis_artifact_id?: string;
    chat_session_id: string;
    content: string;
    created_at: string;
    id: string;
    metadata?: {
        [key: string]: unknown;
    };
    role: string;
    user_id: string;
};

export type SendMessagePayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * AI model ID (for assistant messages)
     */
    ai_model_id?: string;
    /**
     * Message content
     */
    content: string;
    /**
     * Additional metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
    /**
     * Message role (user, assistant, system)
     */
    role: 'user' | 'assistant' | 'system';
};

export type Session = {
    admin_id?: string;
    created_at?: string;
    device_id?: string;
    edges: SessionEdges;
    expires_at?: string;
    id?: string;
    ip_address?: string;
    last_used_at?: string;
    number_of_uses?: number;
    refresh_token?: string;
    revoked_at?: string;
    session_type?: string;
    user_agent?: string;
    user_id?: string;
};

export type SessionEdges = {
    admin?: Admin;
    user?: User;
};

export type ShopeeAnalyzeData = {
    description: string;
    id: string;
    name: string;
};

export type ShopeeAnalyzePayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description: string;
    /**
     * Name of the item
     */
    name: string;
};

export type SubscriptionAiModel = {
    ai_model_id?: string;
    edges: SubscriptionAiModelEdges;
    id?: string;
    subscription_plan_id?: string;
};

export type SubscriptionAiModelEdges = {
    ai_model?: AiModel;
    subscription_plan?: SubscriptionPlan;
};

export type SubscriptionPlan = {
    billing_period?: string;
    created_at?: string;
    description?: string;
    edges: SubscriptionPlanEdges;
    has_advanced_templates?: boolean;
    has_api_access?: boolean;
    has_bulk_import?: boolean;
    has_custom_models?: boolean;
    has_export_pdf?: boolean;
    has_priority_support?: boolean;
    has_sla_guarantee?: boolean;
    has_team_collaboration?: boolean;
    has_white_label?: boolean;
    id?: string;
    is_active?: boolean;
    max_concurrent_sessions?: number;
    max_new_sessions_per_day?: number;
    monthly_token_quota?: number;
    plan_code?: string;
    plan_name?: string;
    price_idr?: number;
    price_usd?: number;
    rollover_expiry_months?: number;
    rollover_percentage?: number;
    scraping_reward_multiplier?: number;
    session_reset_hours?: number;
    session_token_quota?: number;
    updated_at?: string;
};

export type SubscriptionPlanEdges = {
    ai_models?: Array<AiModel> | null;
    subscription_ai_models_rel?: Array<SubscriptionAiModel> | null;
    user_subscription?: Array<UserSubscription> | null;
};

export type TiktokshopAnalyzeData = {
    description: string;
    id: string;
    name: string;
};

export type TiktokshopAnalyzePayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    description: string;
    /**
     * Name of the item
     */
    name: string;
};

export type TokenUsageLog = {
    ai_model_id?: string;
    created_at?: string;
    edges: TokenUsageLogEdges;
    estimated_cost_usd?: number;
    estimated_tokens?: number;
    estimation_accuracy?: number;
    id?: string;
    input_cost_per_million?: number;
    input_tokens?: number;
    message_id?: string;
    output_cost_per_million?: number;
    output_tokens?: number;
    request_type?: string;
    session_id?: string;
    total_cost_usd?: number;
    total_tokens?: number;
    user_id?: string;
};

export type TokenUsageLogEdges = {
    ai_model?: AiModel;
    message?: ChatMessage;
    session?: ChatSession;
    user?: User;
};

export type TokenpediaAnalyzeData = {
    estimated_time?: string;
    job_id?: string;
    marketplace: string;
    metadata?: {
        [key: string]: unknown;
    };
    priority: number;
    product_id: string;
    product_url: string;
    status: string;
    url_hash: string;
};

export type TokenpediaAnalyzePayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Tokopedia product URL
     */
    product_url: string;
    /**
     * Optional user ID for tracking
     */
    user_id?: string;
};

export type TokopediaData = {
    message: string;
};

export type UnreadCountData = {
    description: string;
    id: string;
    name: string;
};

export type UpdateProductPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Current price in IDR
     */
    price_current?: number;
    /**
     * Shop/store name
     */
    shop_name?: string;
    /**
     * Marketplace source
     */
    source?: string;
    /**
     * Product URL
     */
    source_url?: string;
    /**
     * Available stock
     */
    stock?: number;
    /**
     * Product title
     */
    title?: string;
};

export type User = {
    created_at?: string;
    edges: UserEdges;
    email?: string;
    email_verified_at?: string;
    first_name?: string;
    id?: string;
    is_active?: boolean;
    last_name?: string;
    phone_number?: string;
    phone_verified_at?: string;
    updated_at?: string;
};

export type UserEdges = {
    abuse_flags?: Array<AbuseFlag> | null;
    analysis_artifacts?: Array<AnalysisArtifact> | null;
    billing_transactions?: Array<BillingTransaction> | null;
    chat_messages?: Array<ChatMessage> | null;
    chat_sessions?: Array<ChatSession> | null;
    credit_purchases?: Array<CreditPurchase> | null;
    notifications?: Array<Notification> | null;
    product_watchlist?: Array<ProductWatchlist> | null;
    scraping_rewards?: Array<ScrapingReward> | null;
    security_profile?: UserSecurityProfile;
    sessions?: Array<Session> | null;
    subscription?: UserSubscription;
    token_account?: UserTokenAccount;
    token_usage_logs?: Array<TokenUsageLog> | null;
    user_products?: Array<UserProduct> | null;
};

export type UserInformationPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * First name of the user
     */
    first_name: string;
    /**
     * Last name of the user
     */
    last_name: string;
};

export type UserProduct = {
    added_at?: string;
    created_at?: string;
    edges: UserProductEdges;
    id?: string;
    is_priority?: boolean;
    last_viewed_at?: string;
    product_id?: string;
    source_context?: string;
    updated_at?: string;
    user_id?: string;
    view_count?: number;
};

export type UserProductEdges = {
    product?: Product;
    user?: User;
};

export type UserSecurityProfile = {
    created_at?: string;
    edges: UserSecurityProfileEdges;
    failed_login_attempts?: number;
    id?: string;
    last_active_ip?: string;
    last_login_at?: string;
    locked_until?: string;
    max_trial_devices?: number;
    registered_devices?: Array<string> | null;
    signup_ip?: string;
    updated_at?: string;
    user_id?: string;
};

export type UserSecurityProfileEdges = {
    user?: User;
};

export type UserSubscription = {
    auto_renew?: boolean;
    cancellation_reason?: string;
    cancelled_at?: string;
    created_at?: string;
    current_period_end?: string;
    current_period_start?: string;
    edges: UserSubscriptionEdges;
    id?: string;
    status?: string;
    subscription_plan_id?: string;
    trial_ends_at?: string;
    trial_started_at?: string;
    updated_at?: string;
    user_id?: string;
};

export type UserSubscriptionEdges = {
    subscription_plan?: SubscriptionPlan;
    user?: User;
};

export type UserTokenAccount = {
    earned_tokens?: number;
    edges: UserTokenAccountEdges;
    id?: string;
    month_reset_at?: string;
    purchased_credits?: number;
    rollover_expires_at?: string;
    rollover_tokens?: number;
    tokens_used_this_month?: number;
    updated_at?: string;
    user_id?: string;
};

export type UserTokenAccountEdges = {
    user?: User;
};

export type VerifyTokenData = {
    /**
     * Error message if invalid
     */
    error?: string;
    /**
     * User tier (basic/pro/enterprise)
     */
    tier?: string;
    /**
     * User ID from token
     */
    user_id?: string;
    /**
     * Whether the token is valid
     */
    valid: boolean;
};

export type VerifyTokenPayload = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * JWT token to verify
     */
    token: string;
};

export type AddToProductWatchlistPayloadWritable = {
    /**
     * ID of the product to add to watchlist
     */
    product_id: string;
};

export type CacheDeletePayloadWritable = {
    /**
     * Cache key to delete
     */
    key: string;
};

export type CacheGetPayloadWritable = {
    /**
     * Cache key to retrieve
     */
    key: string;
};

export type CacheSetPayloadWritable = {
    /**
     * Cache key to set
     */
    key: string;
    /**
     * Time-to-live in seconds (0 = no expiry)
     */
    ttl_seconds?: number;
    /**
     * Value to cache (JSON serializable)
     */
    value: unknown;
};

export type ChangeUserPasswordPayloadWritable = {
    /**
     * Confirm new password of the user
     */
    confirm_password: string;
    /**
     * Current password of the user
     */
    current_password: string;
    /**
     * New password of the user
     */
    new_password: string;
};

export type CreateProductPayloadWritable = {
    /**
     * Current price in IDR
     */
    price_current?: number;
    /**
     * Shop/store name
     */
    shop_name?: string;
    /**
     * Marketplace source
     */
    source?: string;
    /**
     * Product URL
     */
    source_url?: string;
    /**
     * Available stock
     */
    stock?: number;
    /**
     * Product title
     */
    title?: string;
};

export type CreateSessionOutputWritable = {
    context?: {
        [key: string]: unknown;
    };
    created_at: string;
    id: string;
    session_expires_at?: string;
    session_started_at: string;
    status: string;
    title: string;
    updated_at: string;
    user_id: string;
};

export type CreateSessionPayloadWritable = {
    /**
     * Optional session title
     */
    title: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type ExecuteQueryPayloadWritable = {
    /**
     * Maximum rows to return
     */
    max_rows: number;
    /**
     * Query parameters for safety (not implemented yet)
     */
    parameters?: {
        [key: string]: unknown;
    };
    /**
     * SQL query to execute (SELECT only)
     */
    sql: string;
    /**
     * Query timeout in milliseconds
     */
    timeout_ms: number;
    /**
     * User ID for tracking
     */
    user_id: string;
};

export type GetMessagesOutputWritable = {
    messages: Array<SendMessageOutputWritable> | null;
    total: number;
};

export type ListSessionsOutputWritable = {
    sessions: Array<CreateSessionOutputWritable> | null;
    total: number;
};

export type LogSystemPayloadJobWritable = {
    message: string;
};

export type LoginAdminPayloadWritable = {
    /**
     * Email of the user
     */
    email: string;
    /**
     * Password of the user
     */
    password: string;
};

export type LoginPayloadWritable = {
    /**
     * Email of the user
     */
    email: string;
    /**
     * Password of the user
     */
    password: string;
};

export type MarkAsReadAllPayloadWritable = {
    description: string;
    /**
     * Name of the item
     */
    name: string;
};

export type ProductCalculatePriorityPayloadWritable = {
    /**
     * Product UUID to calculate priority for
     */
    product_id: string;
};

export type ProductHashUrlPayloadWritable = {
    /**
     * Marketplace name
     */
    marketplace: 'tokopedia' | 'shopee' | 'tiktokshop';
    /**
     * Product URL to hash and normalize
     */
    url: string;
};

export type RefreshPayloadWritable = {
    /**
     * The refresh token to use for refreshing the session
     */
    refresh_token: string;
};

export type RegisterPayloadWritable = {
    /**
     * email of user
     */
    email: string;
    /**
     * first name of user
     */
    first_name: string;
    /**
     * last name of user
     */
    last_name: string;
    /**
     * password of user
     */
    password: string;
};

export type ResponseAddToProductWatchlistDataWritable = {
    /**
     * Response data
     */
    data: AddToProductWatchlistData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseAuthRegisterDataWritable = {
    /**
     * Response data
     */
    data: AuthRegisterData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseCacheDeleteDataWritable = {
    /**
     * Response data
     */
    data: CacheDeleteData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseCacheGetDataWritable = {
    /**
     * Response data
     */
    data: CacheGetData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseCacheSetDataWritable = {
    /**
     * Response data
     */
    data: CacheSetData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseCreateProductDataWritable = {
    /**
     * Response data
     */
    data: Product;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseDeleteOneDataWritable = {
    /**
     * Response data
     */
    data: DeleteOneData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseDetailProductDataWritable = {
    /**
     * Response data
     */
    data: DetailProductData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseEventDataWritable = {
    /**
     * Response data
     */
    data: EventData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseExecuteQueryDataWritable = {
    /**
     * Response data
     */
    data: ExecuteQueryData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseHealthDataWritable = {
    /**
     * Response data
     */
    data: HealthData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseJobHttpHandlerDataWritable = {
    /**
     * Response data
     */
    data: JobHttpHandlerData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseLoginAdminDataWritable = {
    /**
     * Response data
     */
    data: LoginAdminOutput;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseLoginDataWritable = {
    /**
     * Response data
     */
    data: LoginData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseMarkAsReadAllDataWritable = {
    /**
     * Response data
     */
    data: MarkAsReadAllData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseMeDataWritable = {
    /**
     * Response data
     */
    data: MeData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseMessageWritable = {
    /**
     * Response message
     */
    message: string;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseNotificationGetAllDataWritable = {
    /**
     * Response data
     */
    data: Array<Notification> | null;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponsePaginationListProductDataWritable = {
    /**
     * Response data
     */
    data: Array<Product> | null;
    /**
     * Response metadata with pagination
     */
    meta: MetaPagination;
};

export type ResponsePaginationListUserProductDataWritable = {
    /**
     * Response data
     */
    data: Array<Product> | null;
    /**
     * Response metadata with pagination
     */
    meta: MetaPagination;
};

export type ResponsePaginationListWatchlistProductDataWritable = {
    /**
     * Response data
     */
    data: Array<Product> | null;
    /**
     * Response metadata with pagination
     */
    meta: MetaPagination;
};

export type ResponseProductCalculatePriorityDataWritable = {
    /**
     * Response data
     */
    data: ProductCalculatePriorityData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseProductDetailChartDataWritable = {
    /**
     * Response data
     */
    data: ProductDetailChartData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseProductHashUrlDataWritable = {
    /**
     * Response data
     */
    data: ProductHashUrlData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseProductOverviewCardDataWritable = {
    /**
     * Response data
     */
    data: ProductOverviewCardData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseRefreshDataWritable = {
    /**
     * Response data
     */
    data: RefreshOutput;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseRemoveProductAsUserProductDataWritable = {
    /**
     * Response data
     */
    data: RemoveProductAsUserProductData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseRemoveProductWatchlistDataWritable = {
    /**
     * Response data
     */
    data: RemoveProductWatchlistData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseShopeeAnalyzeDataWritable = {
    /**
     * Response data
     */
    data: ShopeeAnalyzeData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseTiktokshopAnalyzeDataWritable = {
    /**
     * Response data
     */
    data: TiktokshopAnalyzeData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseTokenpediaAnalyzeDataWritable = {
    /**
     * Response data
     */
    data: TokenpediaAnalyzeData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseTokopediaDataWritable = {
    /**
     * Response data
     */
    data: TokopediaData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseUnreadCountDataWritable = {
    /**
     * Response data
     */
    data: UnreadCountData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type ResponseVerifyTokenDataWritable = {
    /**
     * Response data
     */
    data: VerifyTokenData;
    /**
     * Response metadata
     */
    meta: Meta;
};

export type SendMessageOutputWritable = {
    ai_model_id?: string;
    analysis_artifact_id?: string;
    chat_session_id: string;
    content: string;
    created_at: string;
    id: string;
    metadata?: {
        [key: string]: unknown;
    };
    role: string;
    user_id: string;
};

export type SendMessagePayloadWritable = {
    /**
     * AI model ID (for assistant messages)
     */
    ai_model_id?: string;
    /**
     * Message content
     */
    content: string;
    /**
     * Additional metadata
     */
    metadata?: {
        [key: string]: unknown;
    };
    /**
     * Message role (user, assistant, system)
     */
    role: 'user' | 'assistant' | 'system';
};

export type ShopeeAnalyzePayloadWritable = {
    description: string;
    /**
     * Name of the item
     */
    name: string;
};

export type TiktokshopAnalyzePayloadWritable = {
    description: string;
    /**
     * Name of the item
     */
    name: string;
};

export type TokenpediaAnalyzePayloadWritable = {
    /**
     * Tokopedia product URL
     */
    product_url: string;
    /**
     * Optional user ID for tracking
     */
    user_id?: string;
};

export type UpdateProductPayloadWritable = {
    /**
     * Current price in IDR
     */
    price_current?: number;
    /**
     * Shop/store name
     */
    shop_name?: string;
    /**
     * Marketplace source
     */
    source?: string;
    /**
     * Product URL
     */
    source_url?: string;
    /**
     * Available stock
     */
    stock?: number;
    /**
     * Product title
     */
    title?: string;
};

export type UserInformationPayloadWritable = {
    /**
     * First name of the user
     */
    first_name: string;
    /**
     * Last name of the user
     */
    last_name: string;
};

export type VerifyTokenPayloadWritable = {
    /**
     * JWT token to verify
     */
    token: string;
};

export type PostAdminLoginData = {
    body: LoginAdminPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/admin/login';
};

export type PostAdminLoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostAdminLoginError = PostAdminLoginErrors[keyof PostAdminLoginErrors];

export type PostAdminLoginResponses = {
    /**
     * OK
     */
    200: ResponseLoginAdminData;
};

export type PostAdminLoginResponse = PostAdminLoginResponses[keyof PostAdminLoginResponses];

export type PostAuthLoginData = {
    body: LoginPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: ResponseLoginData;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRefreshData = {
    body: RefreshPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * OK
     */
    200: ResponseRefreshData;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthRegisterData = {
    body: RegisterPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * OK
     */
    200: ResponseAuthRegisterData;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type GetChatSessionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by status (active, expired, archived)
         */
        status?: Array<string | null> | null;
        /**
         * Number of sessions to return (1-100)
         */
        limit?: Array<number> | null;
        /**
         * Number of sessions to skip
         */
        offset?: Array<number> | null;
    };
    url: '/api/chat/sessions';
};

export type GetChatSessionsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetChatSessionsError = GetChatSessionsErrors[keyof GetChatSessionsErrors];

export type GetChatSessionsResponses = {
    /**
     * OK
     */
    200: ListSessionsOutput;
};

export type GetChatSessionsResponse = GetChatSessionsResponses[keyof GetChatSessionsResponses];

export type PostChatSessionsData = {
    body: CreateSessionPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/chat/sessions';
};

export type PostChatSessionsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostChatSessionsError = PostChatSessionsErrors[keyof PostChatSessionsErrors];

export type PostChatSessionsResponses = {
    /**
     * OK
     */
    200: CreateSessionOutput;
};

export type PostChatSessionsResponse = PostChatSessionsResponses[keyof PostChatSessionsResponses];

export type DeleteChatSessionsIdData = {
    body?: never;
    path: {
        /**
         * Session ID
         */
        id: string;
    };
    query?: never;
    url: '/api/chat/sessions/{id}';
};

export type DeleteChatSessionsIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteChatSessionsIdError = DeleteChatSessionsIdErrors[keyof DeleteChatSessionsIdErrors];

export type DeleteChatSessionsIdResponses = {
    /**
     * OK
     */
    200: ResponseMessage;
};

export type DeleteChatSessionsIdResponse = DeleteChatSessionsIdResponses[keyof DeleteChatSessionsIdResponses];

export type GetChatSessionsIdData = {
    body?: never;
    path: {
        /**
         * Session ID
         */
        id: string;
    };
    query?: never;
    url: '/api/chat/sessions/{id}';
};

export type GetChatSessionsIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetChatSessionsIdError = GetChatSessionsIdErrors[keyof GetChatSessionsIdErrors];

export type GetChatSessionsIdResponses = {
    /**
     * OK
     */
    200: CreateSessionOutput;
};

export type GetChatSessionsIdResponse = GetChatSessionsIdResponses[keyof GetChatSessionsIdResponses];

export type GetChatSessionsSessionIdMessagesData = {
    body?: never;
    path: {
        /**
         * Chat session ID
         */
        session_id: string;
    };
    query?: {
        /**
         * Number of messages to return (1-100)
         */
        limit?: Array<number> | null;
        /**
         * Number of messages to skip
         */
        offset?: Array<number> | null;
    };
    url: '/api/chat/sessions/{session_id}/messages';
};

export type GetChatSessionsSessionIdMessagesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetChatSessionsSessionIdMessagesError = GetChatSessionsSessionIdMessagesErrors[keyof GetChatSessionsSessionIdMessagesErrors];

export type GetChatSessionsSessionIdMessagesResponses = {
    /**
     * OK
     */
    200: GetMessagesOutput;
};

export type GetChatSessionsSessionIdMessagesResponse = GetChatSessionsSessionIdMessagesResponses[keyof GetChatSessionsSessionIdMessagesResponses];

export type PostChatSessionsSessionIdMessagesData = {
    body: SendMessagePayloadWritable;
    path: {
        /**
         * Chat session ID
         */
        session_id: string;
    };
    query?: never;
    url: '/api/chat/sessions/{session_id}/messages';
};

export type PostChatSessionsSessionIdMessagesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostChatSessionsSessionIdMessagesError = PostChatSessionsSessionIdMessagesErrors[keyof PostChatSessionsSessionIdMessagesErrors];

export type PostChatSessionsSessionIdMessagesResponses = {
    /**
     * OK
     */
    200: SendMessageOutput;
};

export type PostChatSessionsSessionIdMessagesResponse = PostChatSessionsSessionIdMessagesResponses[keyof PostChatSessionsSessionIdMessagesResponses];

export type DeleteDeleteoneData = {
    body?: never;
    path: {
        /**
         * ID of the item to delete
         */
        id: string;
    };
    query?: never;
    url: '/api/deleteone';
};

export type DeleteDeleteoneErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteDeleteoneError = DeleteDeleteoneErrors[keyof DeleteDeleteoneErrors];

export type DeleteDeleteoneResponses = {
    /**
     * OK
     */
    200: ResponseDeleteOneData;
};

export type DeleteDeleteoneResponse = DeleteDeleteoneResponses[keyof DeleteDeleteoneResponses];

export type GetEnumEventData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/enum/event';
};

export type GetEnumEventErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetEnumEventError = GetEnumEventErrors[keyof GetEnumEventErrors];

export type GetEnumEventResponses = {
    /**
     * OK
     */
    200: ResponseEventData;
};

export type GetEnumEventResponse = GetEnumEventResponses[keyof GetEnumEventResponses];

export type PostExtensionTokopediaData = {
    body?: unknown;
    path?: never;
    query?: never;
    url: '/api/extension/tokopedia';
};

export type PostExtensionTokopediaErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostExtensionTokopediaError = PostExtensionTokopediaErrors[keyof PostExtensionTokopediaErrors];

export type PostExtensionTokopediaResponses = {
    /**
     * OK
     */
    200: ResponseTokopediaData;
};

export type PostExtensionTokopediaResponse = PostExtensionTokopediaResponses[keyof PostExtensionTokopediaResponses];

export type GetGetallData = {
    body?: never;
    path: {
        /**
         * ID of the item
         */
        id: string;
    };
    query?: {
        /**
         * Query parameter for filtering
         */
        q?: string;
    };
    url: '/api/getall';
};

export type GetGetallErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetGetallError = GetGetallErrors[keyof GetGetallErrors];

export type GetGetallResponses = {
    /**
     * OK
     */
    200: ResponseNotificationGetAllData;
};

export type GetGetallResponse = GetGetallResponses[keyof GetGetallResponses];

export type PostInternalAuthVerifyTokenData = {
    body: VerifyTokenPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/internal/auth/verify-token';
};

export type PostInternalAuthVerifyTokenErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostInternalAuthVerifyTokenError = PostInternalAuthVerifyTokenErrors[keyof PostInternalAuthVerifyTokenErrors];

export type PostInternalAuthVerifyTokenResponses = {
    /**
     * OK
     */
    200: ResponseVerifyTokenData;
};

export type PostInternalAuthVerifyTokenResponse = PostInternalAuthVerifyTokenResponses[keyof PostInternalAuthVerifyTokenResponses];

export type DeleteInternalCacheDeleteData = {
    body: CacheDeletePayloadWritable;
    path?: never;
    query?: never;
    url: '/api/internal/cache/delete';
};

export type DeleteInternalCacheDeleteErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteInternalCacheDeleteError = DeleteInternalCacheDeleteErrors[keyof DeleteInternalCacheDeleteErrors];

export type DeleteInternalCacheDeleteResponses = {
    /**
     * OK
     */
    200: ResponseCacheDeleteData;
};

export type DeleteInternalCacheDeleteResponse = DeleteInternalCacheDeleteResponses[keyof DeleteInternalCacheDeleteResponses];

export type PostInternalCacheGetData = {
    body: CacheGetPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/internal/cache/get';
};

export type PostInternalCacheGetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostInternalCacheGetError = PostInternalCacheGetErrors[keyof PostInternalCacheGetErrors];

export type PostInternalCacheGetResponses = {
    /**
     * OK
     */
    200: ResponseCacheGetData;
};

export type PostInternalCacheGetResponse = PostInternalCacheGetResponses[keyof PostInternalCacheGetResponses];

export type PostInternalCacheSetData = {
    body: CacheSetPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/internal/cache/set';
};

export type PostInternalCacheSetErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostInternalCacheSetError = PostInternalCacheSetErrors[keyof PostInternalCacheSetErrors];

export type PostInternalCacheSetResponses = {
    /**
     * OK
     */
    200: ResponseCacheSetData;
};

export type PostInternalCacheSetResponse = PostInternalCacheSetResponses[keyof PostInternalCacheSetResponses];

export type GetInternalHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/health';
};

export type GetInternalHealthErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetInternalHealthError = GetInternalHealthErrors[keyof GetInternalHealthErrors];

export type GetInternalHealthResponses = {
    /**
     * OK
     */
    200: ResponseHealthData;
};

export type GetInternalHealthResponse = GetInternalHealthResponses[keyof GetInternalHealthResponses];

export type PostInternalProductCalculatePriorityData = {
    body: ProductCalculatePriorityPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/internal/product/calculate-priority';
};

export type PostInternalProductCalculatePriorityErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostInternalProductCalculatePriorityError = PostInternalProductCalculatePriorityErrors[keyof PostInternalProductCalculatePriorityErrors];

export type PostInternalProductCalculatePriorityResponses = {
    /**
     * OK
     */
    200: ResponseProductCalculatePriorityData;
};

export type PostInternalProductCalculatePriorityResponse = PostInternalProductCalculatePriorityResponses[keyof PostInternalProductCalculatePriorityResponses];

export type PostInternalProductHashUrlData = {
    body: ProductHashUrlPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/internal/product/hash-url';
};

export type PostInternalProductHashUrlErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostInternalProductHashUrlError = PostInternalProductHashUrlErrors[keyof PostInternalProductHashUrlErrors];

export type PostInternalProductHashUrlResponses = {
    /**
     * OK
     */
    200: ResponseProductHashUrlData;
};

export type PostInternalProductHashUrlResponse = PostInternalProductHashUrlResponses[keyof PostInternalProductHashUrlResponses];

export type PostInternalQueryExecuteSafeData = {
    body: ExecuteQueryPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/internal/query/execute-safe';
};

export type PostInternalQueryExecuteSafeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostInternalQueryExecuteSafeError = PostInternalQueryExecuteSafeErrors[keyof PostInternalQueryExecuteSafeErrors];

export type PostInternalQueryExecuteSafeResponses = {
    /**
     * OK
     */
    200: ResponseExecuteQueryData;
};

export type PostInternalQueryExecuteSafeResponse = PostInternalQueryExecuteSafeResponses[keyof PostInternalQueryExecuteSafeResponses];

export type PostLogSystemData = {
    body: LogSystemPayloadJobWritable;
    headers: {
        'X-Job-Secret': string;
    };
    path?: never;
    query?: never;
    url: '/api/jobs/log_system';
};

export type PostLogSystemErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostLogSystemError = PostLogSystemErrors[keyof PostLogSystemErrors];

export type PostLogSystemResponses = {
    /**
     * OK
     */
    200: ResponseJobHttpHandlerData;
};

export type PostLogSystemResponse = PostLogSystemResponses[keyof PostLogSystemResponses];

export type PostMarkasreadallData = {
    body: MarkAsReadAllPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/markasreadall';
};

export type PostMarkasreadallErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostMarkasreadallError = PostMarkasreadallErrors[keyof PostMarkasreadallErrors];

export type PostMarkasreadallResponses = {
    /**
     * OK
     */
    200: ResponseMarkAsReadAllData;
};

export type PostMarkasreadallResponse = PostMarkasreadallResponses[keyof PostMarkasreadallResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type GetMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: ResponseMeData;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Query parameter for filtering
         */
        q?: string;
    };
    url: '/api/products';
};

export type GetProductsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetProductsError = GetProductsErrors[keyof GetProductsErrors];

export type GetProductsResponses = {
    /**
     * OK
     */
    200: ResponsePaginationListProductData;
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type PostProductsData = {
    body: CreateProductPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/products';
};

export type PostProductsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostProductsError = PostProductsErrors[keyof PostProductsErrors];

export type PostProductsResponses = {
    /**
     * OK
     */
    200: ResponseCreateProductData;
};

export type PostProductsResponse = PostProductsResponses[keyof PostProductsResponses];

export type PutProductsData = {
    body: UpdateProductPayloadWritable;
    path: {
        /**
         * ID of the item to update
         */
        id: string;
    };
    query?: never;
    url: '/api/products';
};

export type PutProductsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PutProductsError = PutProductsErrors[keyof PutProductsErrors];

export type PutProductsResponses = {
    /**
     * OK
     */
    200: ResponseMessage;
};

export type PutProductsResponse = PutProductsResponses[keyof PutProductsResponses];

export type GetProductsMeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Query parameter for filtering
         */
        q?: string;
    };
    url: '/api/products/me';
};

export type GetProductsMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetProductsMeError = GetProductsMeErrors[keyof GetProductsMeErrors];

export type GetProductsMeResponses = {
    /**
     * OK
     */
    200: ResponsePaginationListUserProductData;
};

export type GetProductsMeResponse = GetProductsMeResponses[keyof GetProductsMeResponses];

export type DeleteProductsMeProductIdData = {
    body?: never;
    path?: never;
    query: {
        /**
         * ID of the product to remove as user product
         */
        product_id: string;
    };
    url: '/api/products/me/{product_id}';
};

export type DeleteProductsMeProductIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteProductsMeProductIdError = DeleteProductsMeProductIdErrors[keyof DeleteProductsMeProductIdErrors];

export type DeleteProductsMeProductIdResponses = {
    /**
     * OK
     */
    200: ResponseRemoveProductAsUserProductData;
};

export type DeleteProductsMeProductIdResponse = DeleteProductsMeProductIdResponses[keyof DeleteProductsMeProductIdResponses];

export type GetProductsOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/products/overview';
};

export type GetProductsOverviewErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetProductsOverviewError = GetProductsOverviewErrors[keyof GetProductsOverviewErrors];

export type GetProductsOverviewResponses = {
    /**
     * OK
     */
    200: ResponseProductOverviewCardData;
};

export type GetProductsOverviewResponse = GetProductsOverviewResponses[keyof GetProductsOverviewResponses];

export type GetProductsWatchlistData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Query parameter for filtering
         */
        q?: string;
    };
    url: '/api/products/watchlist';
};

export type GetProductsWatchlistErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetProductsWatchlistError = GetProductsWatchlistErrors[keyof GetProductsWatchlistErrors];

export type GetProductsWatchlistResponses = {
    /**
     * OK
     */
    200: ResponsePaginationListWatchlistProductData;
};

export type GetProductsWatchlistResponse = GetProductsWatchlistResponses[keyof GetProductsWatchlistResponses];

export type PostProductsWatchlistData = {
    body: AddToProductWatchlistPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/products/watchlist';
};

export type PostProductsWatchlistErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostProductsWatchlistError = PostProductsWatchlistErrors[keyof PostProductsWatchlistErrors];

export type PostProductsWatchlistResponses = {
    /**
     * OK
     */
    200: ResponseAddToProductWatchlistData;
};

export type PostProductsWatchlistResponse = PostProductsWatchlistResponses[keyof PostProductsWatchlistResponses];

export type DeleteProductsIdData = {
    body?: never;
    path: {
        /**
         * ID of the item to delete
         */
        id: string;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type DeleteProductsIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteProductsIdError = DeleteProductsIdErrors[keyof DeleteProductsIdErrors];

export type DeleteProductsIdResponses = {
    /**
     * OK
     */
    200: ResponseMessage;
};

export type DeleteProductsIdResponse = DeleteProductsIdResponses[keyof DeleteProductsIdResponses];

export type GetProductsIdData = {
    body?: never;
    path: {
        /**
         * ID of the item
         */
        id: string;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type GetProductsIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetProductsIdError = GetProductsIdErrors[keyof GetProductsIdErrors];

export type GetProductsIdResponses = {
    /**
     * OK
     */
    200: ResponseDetailProductData;
};

export type GetProductsIdResponse = GetProductsIdResponses[keyof GetProductsIdResponses];

export type GetProductsIdChartData = {
    body?: never;
    path: {
        /**
         * Product ID
         */
        id: string;
    };
    query?: {
        /**
         * Month for chart data (0-11), defaults to current month
         */
        month?: number;
    };
    url: '/api/products/{id}/chart';
};

export type GetProductsIdChartErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetProductsIdChartError = GetProductsIdChartErrors[keyof GetProductsIdChartErrors];

export type GetProductsIdChartResponses = {
    /**
     * OK
     */
    200: ResponseProductDetailChartData;
};

export type GetProductsIdChartResponse = GetProductsIdChartResponses[keyof GetProductsIdChartResponses];

export type PostShopeeanalyzeData = {
    body: ShopeeAnalyzePayloadWritable;
    path?: never;
    query?: never;
    url: '/api/shopeeanalyze';
};

export type PostShopeeanalyzeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostShopeeanalyzeError = PostShopeeanalyzeErrors[keyof PostShopeeanalyzeErrors];

export type PostShopeeanalyzeResponses = {
    /**
     * OK
     */
    200: ResponseShopeeAnalyzeData;
};

export type PostShopeeanalyzeResponse = PostShopeeanalyzeResponses[keyof PostShopeeanalyzeResponses];

export type PostTiktokshopanalyzeData = {
    body: TiktokshopAnalyzePayloadWritable;
    path?: never;
    query?: never;
    url: '/api/tiktokshopanalyze';
};

export type PostTiktokshopanalyzeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostTiktokshopanalyzeError = PostTiktokshopanalyzeErrors[keyof PostTiktokshopanalyzeErrors];

export type PostTiktokshopanalyzeResponses = {
    /**
     * OK
     */
    200: ResponseTiktokshopAnalyzeData;
};

export type PostTiktokshopanalyzeResponse = PostTiktokshopanalyzeResponses[keyof PostTiktokshopanalyzeResponses];

export type GetUnreadcountData = {
    body?: never;
    path: {
        /**
         * ID of the item
         */
        id: string;
    };
    query?: {
        /**
         * Query parameter for filtering
         */
        q?: string;
    };
    url: '/api/unreadcount';
};

export type GetUnreadcountErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetUnreadcountError = GetUnreadcountErrors[keyof GetUnreadcountErrors];

export type GetUnreadcountResponses = {
    /**
     * OK
     */
    200: ResponseUnreadCountData;
};

export type GetUnreadcountResponse = GetUnreadcountResponses[keyof GetUnreadcountResponses];

export type PostUsersChangePasswordData = {
    body: ChangeUserPasswordPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/users/change-password';
};

export type PostUsersChangePasswordErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostUsersChangePasswordError = PostUsersChangePasswordErrors[keyof PostUsersChangePasswordErrors];

export type PostUsersChangePasswordResponses = {
    /**
     * OK
     */
    200: ResponseMessage;
};

export type PostUsersChangePasswordResponse = PostUsersChangePasswordResponses[keyof PostUsersChangePasswordResponses];

export type PutUsersInformationData = {
    body: UserInformationPayloadWritable;
    path?: never;
    query?: never;
    url: '/api/users/information';
};

export type PutUsersInformationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PutUsersInformationError = PutUsersInformationErrors[keyof PutUsersInformationErrors];

export type PutUsersInformationResponses = {
    /**
     * OK
     */
    200: ResponseMessage;
};

export type PutUsersInformationResponse = PutUsersInformationResponses[keyof PutUsersInformationResponses];

export type DeleteProductsWatchlistProductIdData = {
    body?: never;
    path?: never;
    query: {
        /**
         * ID of the product to remove from watchlist
         */
        product_id: string;
    };
    url: '/apiproducts/watchlist/{product_id}';
};

export type DeleteProductsWatchlistProductIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteProductsWatchlistProductIdError = DeleteProductsWatchlistProductIdErrors[keyof DeleteProductsWatchlistProductIdErrors];

export type DeleteProductsWatchlistProductIdResponses = {
    /**
     * OK
     */
    200: ResponseRemoveProductWatchlistData;
};

export type DeleteProductsWatchlistProductIdResponse = DeleteProductsWatchlistProductIdResponses[keyof DeleteProductsWatchlistProductIdResponses];
